public class TryCatchExample9{
public static void main(Strainng args[]){
Try;
{
int arr[]=(1,3,5,7);
System.out.println(arr[10]);
}
Catch(arrayIndexOutOfBounds Exception e)
{
System.out.println(e);
}
System.out.println("rest of the code");
}
}
